version: "3"
services:
  app:
    image: jilexandr/natsavrotester:1.1.2
    environment:
      PORT: 8080
      NATS_SERVER: "http://nats:4222"
      MAX_HIERARCHY_LEVEL: 5
      LOG_LEVEL: "trace"
    ports:
      - 9999:8080
    links:
      - nats
  nats:
    image: nats:2.1
    ports:
      - 4222